###Nama         : Septavia Navis

###NIM 		     : 212410103039

###Kelas 	     : Kecerdasan Komputasional B

                                  Modul 6
                  Konsep Data Engineering, Data Warehouse dan SQL

**TUGAS**
1. ulangi langkah pada kode 1 untuk dataset iris dan gunakan perbandingan 0.2, 0.3, 0.4. tuliskan akurasinya
2. untuk dataset iris carilah subset kombinasi dari attribut yang memeberi hasil klasifikasi lebih baik dari data asli

**JAWAB**

### 1. ulangi langkah pada kode 1 untuk dataset iris dan gunakan perbandingan 0.2, 0.3, 0.4. tuliskan akurasinya

In [ ]:
#Blok1

import pandas as pd
from sklearn.datasets import load_iris

iris = load_iris()
df = pd.DataFrame(iris.data, columns=iris.feature_names)
df['target'] = iris.target
df.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0

- ***import pandas as pd*** : Mengimport library pandas dengan alias pd untuk digunakan dalam kode.
- ***from sklearn.datasets import load_iris*** : Mengimport fungsi load_iris dari modul sklearn.datasets. Fungsi ini digunakan untuk memuat dataset bawaan Iris.
- ***iris = load_iris()*** : Memuat dataset Iris menggunakan fungsi load_iris() dan menyimpannya ke dalam variabel iris.
- ***df = pd.DataFrame(iris.data, columns=iris.feature_names)*** : Membentuk DataFrame dari data iris dengan menggunakan fungsi pd.DataFrame. Data iris terdiri dari fitur-fitur yang diukur, yang diberikan oleh iris.data, dan nama fitur-fiturnya disimpan dalam iris.feature_names. DataFrame ini akan memiliki kolom-kolom yang sesuai dengan nama fitur-fitur iris.
- ***df['target'] = iris.target*** : Menambahkan kolom baru dengan nama 'target' ke DataFrame df yang berisi target kelas untuk setiap sampel dalam dataset iris. Nilai target disimpan dalam iris.target, yang merupakan array yang sesuai dengan setiap sampel dalam dataset iris.
- ***df.head()*** : Menampilkan beberapa baris teratas dari DataFrame df untuk melihat data Iris secara ringkas.

In [ ]:
#Blok2

df.drop(['sepal length (cm)','sepal width (cm)','target'],axis='columns',inplace=True)
df.head()

   petal length (cm)  petal width (cm)
0                1.4               0.2
1                1.4               0.2
2                1.3               0.2
3                1.5               0.2
4                1.4               0.2

- ***df.drop(['sepal length (cm)','sepal width (cm)','target'], axis='columns', inplace=True)*** : Fungsi drop() digunakan untuk menghapus kolom-kolom yang diberikan dari DataFrame. Di sini, kita memberikan daftar kolom yang ingin dihapus, yaitu 'sepal length (cm)', 'sepal width (cm)', dan 'target'. Argumen axis='columns' menunjukkan bahwa kita ingin menghapus kolom, bukan baris. Argumen inplace=True mengindikasikan bahwa perubahan akan dilakukan secara langsung pada DataFrame df, tanpa perlu membuat DataFrame baru. Akibatnya, DataFrame df akan dimutakhirkan dengan kolom-kolom yang dihapus.
- ***df.head()*** : Menampilkan lima baris pertama dari DataFrame df yang telah dimutakhirkan setelah kolom-kolom dihapus. Fungsi head() digunakan untuk melihat beberapa baris awal dari DataFrame.

In [ ]:
#Blok3

inputs = df
target = iris.target

- ***inputs = df*** : Menyimpan DataFrame df ke dalam variabel inputs. DataFrame df berisi data atribut dari dataset iris.
- ***target = iris_target*** : Menyimpan array iris_target ke dalam variabel target. Array iris_target berisi target atau label dari dataset iris, yang menunjukkan kelas atau spesies dari setiap sampel iris.

In [ ]:
#Blok4

dummies = pd.get_dummies(inputs['petal width (cm)'], prefix='petal_width')
dummies.head(3)

,petal_width_0.1,petal_width_0.2,petal_width_0.3,petal_width_0.4,petal_width_0.5,petal_width_0.6,petal_width_1.0,petal_width_1.1,petal_width_1.2,petal_width_1.3,...,petal_width_1.6,petal_width_1.7,petal_width_1.8,petal_width_1.9,petal_width_2.0,petal_width_2.1,petal_width_2.2,petal_width_2.3,petal_width_2.4,petal_width_2.5
0,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

- ***dummies = pd.get_dummies(inputs['petal width (cm)'], prefix='petal_width')*** : Menggunakan fungsi get_dummies dari pandas untuk melakukan one-hot encoding pada kolom 'petal width (cm)' dari DataFrame inputs. Fungsi ini akan menghasilkan variabel dummy untuk setiap nilai unik dalam kolom tersebut. Parameter prefix='petal_width' digunakan untuk memberikan awalan pada nama variabel dummy yang dihasilkan.
- ***dummies.head(3)*** : Menampilkan tiga baris pertama dari DataFrame dummies, yang berisi hasil dari one-hot encoding kolom 'petal width (cm)'.

In [ ]:
#Blok5

inputs = pd.concat([inputs,dummies],axis='columns')
inputs.head(3)

,petal length (cm),petal width (cm),petal_width_0.1,petal_width_0.2,petal_width_0.3,petal_width_0.4,petal_width_0.5,petal_width_0.6,petal_width_1.0,petal_width_1.1,...,petal_width_1.6,petal_width_1.7,petal_width_1.8,petal_width_1.9,petal_width_2.0,petal_width_2.1,petal_width_2.2,petal_width_2.3,petal_width_2.4,petal_width_2.5
0,1.4,0.2,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1.4,0.2,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1.3,0.2,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

- ***inputs = pd.concat([inputs,dummies],axis='columns')*** : Menggunakan fungsi concat dari pandas untuk menggabungkan DataFrame inputs dan DataFrame dummies secara horizontal (berdasarkan kolom) dengan menggunakan parameter axis='columns'. Ini akan menghasilkan DataFrame baru yang terdiri dari kolom-kolom dari inputs dan kolom-kolom dari dummies yang ditambahkan ke bagian kanan inputs.
- ***inputs.head(3)*** : Menampilkan tiga baris pertama dari DataFrame inputs yang telah digabungkan dengan kolom-kolom dari dummies.

In [ ]:
#Blok6

inputs.drop(['petal width (cm)'],axis='columns',inplace=True)
inputs.head(3)

,petal length (cm),petal_width_0.1,petal_width_0.2,petal_width_0.3,petal_width_0.4,petal_width_0.5,petal_width_0.6,petal_width_1.0,petal_width_1.1,petal_width_1.2,...,petal_width_1.6,petal_width_1.7,petal_width_1.8,petal_width_1.9,petal_width_2.0,petal_width_2.1,petal_width_2.2,petal_width_2.3,petal_width_2.4,petal_width_2.5
0,1.4,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1.4,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1.3,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

- ***inputs.drop(['petal width (cm)'], axis='columns', inplace=True)*** : Fungsi drop() digunakan untuk menghapus kolom yang diberikan dari DataFrame. Di sini, kita memberikan daftar kolom yang ingin dihapus, yaitu 'petal width (cm)'. Argumen axis='columns' menunjukkan bahwa kita ingin menghapus kolom, bukan baris. Argumen inplace=True mengindikasikan bahwa perubahan akan dilakukan secara langsung pada DataFrame inputs, tanpa perlu membuat DataFrame baru. Akibatnya, DataFrame inputs akan dimutakhirkan dengan kolom 'petal width (cm)' yang dihapus.
- ***inputs.head(3)*** : Menampilkan tiga baris pertama dari DataFrame inputs yang telah digabungkan dengan kolom-kolom dari dummies.

In [ ]:
#Blok7

inputs.columns[inputs.isna().any()]

Index([], dtype='object')

- ***inputs.columns[inputs.isna().any()]*** : Mengakses atribut columns dari DataFrame inputs, yang mengembalikan daftar nama kolom dalam DataFrame.. Menggunakan metode isna() pada DataFrame inputs untuk mendeteksi nilai yang hilang (NaN) dalam setiap kolom. Metode any() kemudian digunakan untuk mengecek apakah ada nilai yang hilang (True) dalam setiap kolom. Hasilnya adalah sebuah Series boolean yang menunjukkan apakah setiap kolom memiliki nilai yang hilang atau tidak.

In [ ]:
#Blok8

inputs['petal length (cm)'][:20]

0     1.4
1     1.4
2     1.3
3     1.5
4     1.4
5     1.7
6     1.4
7     1.5
8     1.4
9     1.5
10    1.5
11    1.6
12    1.4
13    1.1
14    1.2
15    1.5
16    1.3
17    1.4
18    1.7
19    1.5
Name: petal length (cm), dtype: float64

- ***inputs['petal length (cm)']*** : Mengakses kolom dengan nama 'petal length (cm)' dari DataFrame inputs. Ini mengembalikan Seri yang berisi nilai-nilai dalam kolom tersebut.
- **[:20]** : Menggunakan slicing untuk membatasi Seri hanya pada 20 baris pertama. Ini menghasilkan Seri yang berisi 20 nilai pertama dalam kolom 'petal length (cm)'.

In [ ]:
#Blok9

inputs['petal length (cm)'] = inputs['petal length (cm)'].fillna(inputs['petal length (cm)'].mean())
inputs.head()

,petal length (cm),petal_width_0.1,petal_width_0.2,petal_width_0.3,petal_width_0.4,petal_width_0.5,petal_width_0.6,petal_width_1.0,petal_width_1.1,petal_width_1.2,...,petal_width_1.6,petal_width_1.7,petal_width_1.8,petal_width_1.9,petal_width_2.0,petal_width_2.1,petal_width_2.2,petal_width_2.3,petal_width_2.4,petal_width_2.5
0,1.4,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1.4,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1.3,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,1.5,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,1.4,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

- ***inputs['petal length (cm)']*** : Mengakses kolom 'petal length (cm)' dari DataFrame inputs.
- ***.fillna(inputs['petal length (cm)'].mean())*** : Fungsi fillna() digunakan untuk mengisi nilai yang hilang. Di sini, kita menggunakan metode .mean() pada kolom 'petal length (cm)' untuk menghitung nilai rata-ratanya.
- ***inputs['petal length (cm)'] = ...*** : Mengassign nilai yang telah diisi ke dalam kolom 'petal length (cm)' dari DataFrame inputs. Dengan melakukan ini, kita mengganti nilai yang hilang dengan nilai rata-rata.
- ***inputs.head()*** : Menampilkan lima baris pertama dari DataFrame inputs yang telah dimutakhirkan. Fungsi head() digunakan untuk melihat beberapa baris awal dari DataFrame.

In [ ]:
#Blok10

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(inputs,target,test_size=0.2, random_state=0)
X_train_2, X_test_2, y_train_2, y_test_2 = train_test_split(inputs,target,test_size=0.3, random_state=0)
X_train_3, X_test_3, y_train_3, y_test_3 = train_test_split(inputs,target,test_size=0.4, random_state=0)

- ***from sklearn.model_selection import train_test_split*** : Mengimpor fungsi train_test_split dari modul sklearn.model_selection. Fungsi ini digunakan untuk membagi dataset menjadi data latih dan data uji.
- ***X_train, X_test, y_train, y_test = train_test_split(inputs, target, test_size=0.2, random_state=0)*** : Memanggil fungsi train_test_split dengan argumen inputs, target, test_size=0.2, dan random_state=0. Ini akan membagi dataset inputs dan target menjadi data latih dan data uji dengan rasio 80:20. Variabel X_train akan berisi data latih fitur (atribut), X_test akan berisi data uji fitur, y_train akan berisi data latih target, dan y_test akan berisi data uji target.
- ***X_train_2, X_test_2, y_train_2, y_test_2 = train_test_split(inputs, target, test_size=0.3, random_state=0)*** : Memanggil fungsi train_test_split dengan argumen yang sama, tetapi dengan test_size=0.3. Ini akan membagi dataset menjadi data latih dan data uji dengan rasio 70:30. Variabel X_train_2, X_test_2, y_train_2, dan y_test_2 akan berisi data latih dan data uji yang baru.
- ***X_train_3, X_test_3, y_train_3, y_test_3 = train_test_split(inputs, target, test_size=0.4, random_state=0)*** : Memanggil fungsi train_test_split dengan test_size=0.4. Ini akan membagi dataset menjadi data latih dan data uji dengan rasio 60:40. Variabel X_train_3, X_test_3, y_train_3, dan y_test_3 akan berisi data latih dan data uji yang baru.

In [ ]:
#Blok11

from sklearn.naive_bayes import GaussianNB
model = GaussianNB()
model.fit(X_train,y_train)
model.score(X_test,y_test)

model_2 = GaussianNB()
model_2.fit(X_train_2,y_train_2)
model_2.score(X_test_2,y_test_2)

model_3 = GaussianNB()
model_3.fit(X_train_3,y_train_3)
model_3.score(X_test_3,y_test_3)

print(f"Akurasi model ketika test_size=0.2 : {model.score(X_test,y_test)}")
print(f"Akurasi model ketika test_size=0.3 : {model.score(X_test_2,y_test_2)}")
print(f"Akurasi model ketika test_size=0.4 : {model.score(X_test_3,y_test_3)}")

Akurasi model ketika test_size=0.2 : 0.9666666666666667
Akurasi model ketika test_size=0.3 : 0.9777777777777777
Akurasi model ketika test_size=0.4 : 0.9333333333333333

- ***from sklearn.naive_bayes import GaussianNB*** : Mengimpor kelas GaussianNB dari modul sklearn.naive_bayes. GaussianNB adalah implementasi Naive Bayes dengan asumsi distribusi Gaussian (normal).
- ***model = GaussianNB()*** : Membuat objek model Naive Bayes dengan menggunakan kelas GaussianNB().
- ***model.fit(X_train, y_train)*** : Melatih model menggunakan data latih X_train dan target latih y_train. Model akan belajar untuk memahami hubungan antara fitur dan target.
- ***model.score(X_test, y_test)*** : Menghitung akurasi model pada data uji dengan menggunakan metode score. Metode ini akan menghitung seberapa baik model memprediksi target pada data uji. Nilai akurasi yang dihasilkan adalah proporsi prediksi yang benar.
- ***model_2 = GaussianNB()*** : Membuat objek model Naive Bayes yang kedua untuk rasio test_size=0.3.
- ***model_2.fit(X_train_2, y_train_2)*** : Melatih model kedua menggunakan data latih dan target yang sesuai dengan rasio test_size=0.3.
- ***model_2.score(X_test_2, y_test_2)*** : Menghitung akurasi model kedua pada data uji yang sesuai dengan rasio test_size=0.3.
- ***model_3 = GaussianNB()*** : Membuat objek model Naive Bayes yang ketiga untuk rasio test_size=0.4.
- ***model_3.fit(X_train_3, y_train_3)*** : Melatih model ketiga menggunakan data latih dan target yang sesuai dengan rasio test_size=0.4.
- ***model_3.score(X_test_3, y_test_3)*** : Menghitung akurasi model ketiga pada data uji yang sesuai dengan rasio test_size=0.4.
- ***print(f"Akurasi model ketika test_size=0.2 : {model.score(X_test, y_test)}")*** : Menampilkan akurasi model pertama pada data uji dengan rasio test_size=0.2.
- ***print(f"Akurasi model ketika test_size=0.3 : {model.score(X_test_2, y_test_2)}")*** : Menampilkan akurasi model kedua pada data uji dengan rasio test_size=0.3.
- ***print(f"Akurasi model ketika test_size=0.4 : {model.score(X_test_3, y_test_3)}")*** : Menampilkan akurasi model ketiga pada data uji dengan rasio test_size=0.4.

In [ ]:
#Blok12

X_test[0:10]

,petal length (cm),petal_width_0.1,petal_width_0.2,petal_width_0.3,petal_width_0.4,petal_width_0.5,petal_width_0.6,petal_width_1.0,petal_width_1.1,petal_width_1.2,...,petal_width_1.6,petal_width_1.7,petal_width_1.8,petal_width_1.9,petal_width_2.0,petal_width_2.1,petal_width_2.2,petal_width_2.3,petal_width_2.4,petal_width_2.5
114,5.1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
62,4.0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
33,1.4,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
107,6.3,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
7,1.5,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
100,6.0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
40,1.3,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
86,4.7,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
76,4.8,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
71,4.0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

- ***X_test[0:10]*** : Mengambil subset dari data uji X_test dengan indeks baris dari 0 hingga 9. Ini akan menghasilkan 10 baris pertama dari data uji.

In [ ]:
#Blok13

y_test[0:10]

- ***y_test[0:10]*** : Mengambil subset dari target variabel uji y_test dengan indeks baris dari 0 hingga 9. Ini akan menghasilkan 10 nilai target pertama dari data uji.

In [ ]:
#Blok14

model.predict(X_test[0:10])

- ***model.predict(X_test[0:10])*** : Memanggil metode predict() dari model yang telah dilatih dengan argumen data uji X_test yang diambil subsetnya dari indeks baris 0 hingga 9. Ini akan menghasilkan prediksi kelas untuk subset data uji yang diberikan.

In [ ]:
#Blok15

model.predict_proba(X_test[:10])

- ***model.predict_proba(X_test[:10])*** : Memanggil metode predict_proba() dari model yang telah dilatih dengan argumen data uji X_test yang diambil subsetnya dari indeks baris 0 hingga 9. Metode predict_proba() menghasilkan probabilitas untuk setiap kelas pada subset data uji.

###2. untuk dataset iris carilah subset kombinasi dari attribut yang memeberi hasil klasifikasi lebih baik dari data asli

In [ ]:
from sklearn.feature_selection import RFE
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.datasets import load_iris
import pandas as pd

# Load dataset iris
iris = load_iris()

# Membuat DataFrame dari dataset
iris_df = pd.DataFrame(iris.data, columns=iris.feature_names)

# Membuat target variable
target = iris.target

# Membuat model pembelajaran mesin (Random Forest Classifier)
model = RandomForestClassifier()

# Menerapkan Recursive Feature Elimination (RFE) dengan model yang telah ditentukan
rfe = RFE(estimator=model, n_features_to_select=2)
rfe.fit(iris_df, target)

# Menampilkan hasil subset kombinasi atribut terbaik
selected_features = iris_df.columns[rfe.support_]
print("Subset kombinasi atribut terbaik:")
for feature in selected_features:
    print(feature)

# Split data menjadi training dan testing
X_train, X_test, y_train, y_test = train_test_split(iris_df[selected_features], target, test_size=0.4, random_state=0)

# Membuat dictionary untuk menyimpan akurasi dari setiap kombinasi atribut
attribute_combination_scores = {}

# Melakukan klasifikasi menggunakan Gaussian Naive Bayes untuk setiap kombinasi atribut dan menyimpan skor akurasinya
for attributes in selected_features:
    model = GaussianNB()
    model.fit(X_train[[attributes]], y_train)
    score = model.score(X_test[[attributes]], y_test)
    attribute_combination_scores[str([attributes])] = score

print(' ')
# Menampilkan akurasi dari setiap kombinasi atribut yang telah dicoba
for attributes, score in attribute_combination_scores.items():
    print("Subset kombinasi atribut terbaik:", attributes)
    print("Akurasi:", score)
    print()

Subset kombinasi atribut terbaik:
petal length (cm)
petal width (cm)

Subset kombinasi atribut terbaik: ['petal length (cm)']
Akurasi: 0.9

Subset kombinasi atribut terbaik: ['petal width (cm)']
Akurasi: 0.9333333333333333

Dalam kode di atas, pertama-tama kita menerapkan Recursive Feature Elimination (RFE) menggunakan Random Forest Classifier untuk memilih subset kombinasi atribut terbaik dari dataset iris. Selanjutnya, kita membagi data menjadi training dan testing menggunakan train_test_split. Kemudian, kita melakukan klasifikasi menggunakan Gaussian Naive Bayes untuk setiap kombinasi atribut yang telah ditentukan, dan menyimpan skor akurasinya dalam dictionary attribute_combination_scores. Terakhir, kita mencetak hasil subset kombinasi atribut terbaik dan akurasinya menggunakan loop for.